CREATE DATABASE MUNDO;

CREATE TABLE PAISES
(
	COD SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(100),
	HABITANTES NUMERIC(10)
);

INSERT INTO PAISES
(NOMBRE, HABITANTES)
VALUES
('República Checa', 10501197);

INSERT INTO PAISES
(NOMBRE, HABITANTES)
VALUES
('Malta', 475700);
