-- Adrián Navarro Gabino

/*
 * It can be seen that the Client and Official entities are special
 * specializations of the "superentity" of Persons, so that both clients
 * and officials would inherit their attributes. However, the "People"
 * entity would correspond to a generalization of Clients and Officials
 * which does not have specific attributes of the "sub-entities".
 *
 * Create the three corresponding tables with their attributes and
 * inheritances. Also, enter sample data.
 */

CREATE TABLE PERSONAS
(
	NUMERO SERIAL PRIMARY KEY,
	NOMBRES VARCHAR(50),
	APELLIDOS VARCHAR(60),
	DIRECCION VARCHAR(100),
	TELEFONO NUMERIC(12),
	FECHA_NACIM DATE
);

CREATE TABLE CLIENTES
(
	NRO_CUENTA VARCHAR(24),
	ESTADO VARCHAR(10),
	TIPO_CLIENTE VARCHAR(10)
)
INHERITS (PERSONAS);

ALTER TABLE CLIENTES
ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (NUMERO);

CREATE TABLE FUNCIONARIOS
(
	CARGO VARCHAR(20),
	FECHA_INGRESO DATE,
	DEPARTAMENTO VARCHAR(20)
)
INHERITS (PERSONAS);

ALTER TABLE FUNCIONARIOS
ADD CONSTRAINT PK_FUNCIONARIOS PRIMARY KEY (NUMERO);

INSERT INTO PERSONAS
(NOMBRES, APELLIDOS, DIRECCION)
VALUES
('NAME PERSONAS 1', 'SURNAME PERSONAS 1', 'STREET PERSONAS 1');

INSERT INTO PERSONAS
(NOMBRES, APELLIDOS, DIRECCION)
VALUES
('NAME PERSONAS 2', 'SURNAME PERSONAS 2', 'STREET PERSONAS 2');

INSERT INTO CLIENTES
(NOMBRES, APELLIDOS, DIRECCION, TIPO_CLIENTE)
VALUES
('NAME CLIENTES 1', 'SURNAME CLIENTES 1',
 'STREET CLIENTES 1', 'TIPO_CLI 1');

INSERT INTO FUNCIONARIOS
(NOMBRES, APELLIDOS, DIRECCION, DEPARTAMENTO)
VALUES
('NAME FUNCIONARIOS 1', 'SURNAME FUNCIONARIOS 1',
 'STREET FUNCIONARIOS 1', 'DEPT FUNC 1');
 
SELECT * FROM PERSONAS;
SELECT * FROM ONLY PERSONAS;
SELECT * FROM CLIENTES;
SELECT * FROM FUNCIONARIOS;