package com.adriannavarrogabino.peliculas;
// Generated 10 ene. 2020 11:48:06 by Hibernate Tools 4.3.1



/**
 * Peliculas generated by hbm2java
 */
public class Peliculas  implements java.io.Serializable {


     private String nombre;
     private Tematicas tematicas;
     private Integer puntuacion;
     private Integer duracion;

    public Peliculas() {
    }

	
    public Peliculas(String nombre) {
        this.nombre = nombre;
    }
    public Peliculas(String nombre, Tematicas tematicas, Integer puntuacion, Integer duracion) {
       this.nombre = nombre;
       this.tematicas = tematicas;
       this.puntuacion = puntuacion;
       this.duracion = duracion;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Tematicas getTematicas() {
        return this.tematicas;
    }
    
    public void setTematicas(Tematicas tematicas) {
        this.tematicas = tematicas;
    }
    public Integer getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(Integer puntuacion) {
        this.puntuacion = puntuacion;
    }
    public Integer getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Integer duracion) {
        this.duracion = duracion;
    }

    @Override
    public String toString() {
        return "Peliculas{" + "nombre=" + nombre + ", tematicas=" +
                tematicas.getNombre() + ", puntuacion=" + puntuacion +
                ", duracion=" + duracion + '}';
    }


}


