package com.adriannavarrogabino.peliculas;
// Generated 10 ene. 2020 11:48:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.*;
import java.util.Set;

/**
 * Tematicas generated by hbm2java
 */
public class Tematicas  implements java.io.Serializable {


     private String nombre;
     private Set<Peliculas> peliculases = new HashSet(0);

    public Tematicas() {
    }

	
    public Tematicas(String nombre) {
        this.nombre = nombre;
    }
    public Tematicas(String nombre, Set peliculases) {
       this.nombre = nombre;
       this.peliculases = peliculases;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPeliculases() {
        return this.peliculases;
    }
    
    public void setPeliculases(Set peliculases) {
        this.peliculases = peliculases;
    }

    @Override
    public String toString() {
        List<Peliculas> peliculas = new ArrayList<>();
        String result = "";
        
        for(Peliculas p: peliculases)
        {
            result += p + "\n";
        }
        
        return "Tematicas{" + "nombre=" + nombre + "\npeliculas=" + result +
                "}";
    }

    


}


